TWEAK_NAME = KayokoHelper
KayokoHelper_FILES = KayokoHelper.xm
KayokoHelper_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
KayokoHelper_FRAMEWORKS = UIKit
KayokoHelper_EXTRA_FRAMEWORKS = Cephei

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/aggregate.mk
include $(THEOS_MAKE_PATH)/tweak.mk
