TOOL_NAME = kayokod
kayokod_FILES = KayokoDaemon.m
kayokod_INSTALL_PATH = /usr/libexec
kayokod_CODESIGN_FLAGS = -Sentitlements.plist

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tool.mk
