#!/bin/sh

if [ -d /var/mobile/Documents/dev.traurige/ ]; then
    chown -R mobile:mobile /var/mobile/Documents/dev.traurige/
fi

if [[ -e /Library/LaunchDaemons/dev.traurige.kayokod.plist ]]; then
    launchctl load /Library/LaunchDaemons/dev.traurige.kayokod.plist;
elif [[ -e /var/jb/Library/LaunchDaemons/dev.traurige.kayokod.plist ]]; then
    launchctl load /var/jb/Library/LaunchDaemons/dev.traurige.kayokod.plist;
fi
